name: multi_link_text
description: A Flutter package multi_link_text allows you to create text with clickable links and additional styling options.
version: 0.0.2
homepage: https://github.com/therasuldev/multi-link-text
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: